Repository spectreconsole/spectre.console, pull requests merged in 2024-11, with the labels that each got.

#1675 Adding Enricher for Azure Pipelines
  src/Spectre.Console/Enrichment/CI/AzurePipelinesEnricher.cs
  src/Spectre.Console/Enrichment/ProfileEnricher.cs
Labels: :star: top pull request

#904 Adding TransferSpeedColumn configuration to display bits/bytes + binary/decimal prefixes
  docs/input/live/progress.md
  src/Spectre.Console/Internal/FileSize.cs
  src/Spectre.Console/Internal/FileSizeBase.cs
  src/Spectre.Console/Internal/FileSizePrefix.cs
  src/Spectre.Console/Internal/FileSizeUnit.cs
  src/Spectre.Console/Live/Progress/Columns/DownloadedColumn.cs
  src/Spectre.Console/Live/Progress/Columns/TransferSpeedColumn.cs
  src/Tests/Spectre.Console.Tests/Unit/Internal/FileSizeTests.cs
  src/Tests/Spectre.Console.Tests/Unit/Live/Progress/DownloadedColumnTests.cs
Labels: feature

#1694 ProgressTask.GetPercentage() returns 100 when max value is 0
  src/Spectre.Console/Live/Progress/ProgressTask.cs
  src/Tests/Spectre.Console.Tests/Unit/Live/Progress/ProgressTests.cs
Labels: bug

#1194 Async overloads for AnsiConsole Prompt/Ask/Confirm.
  src/Spectre.Console/AnsiConsole.Prompt.cs
  src/Spectre.Console/Extensions/AnsiConsoleExtensions.Prompt.cs
  src/Tests/Spectre.Console.Tests/Unit/AnsiConsoleTests.Prompt.cs
Labels: :star: top pull request
